name: urban-demand-forecasting

channels:
  - defaults

dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - matplotlib
      - scipy
      - shap
      - joblib
      - xgboost
      - lightgbm
      - notebook
      - tqdm
